#!/usr/bin/env bash
# Bash script to install and configure HAproxy on your lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8\*

echo "
frontend http
 bind *:80
 stats uri /haproxy?stats
 default_backend web-backend
backend web-backend
balance roundrobin
server 39708-web-01 3.95.131.223 check
server 39708-web-02 100.26.165.206 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
