#!/usr/bin/env bash
# displays school School 100 times.

COUNTER=1
while [ $COUNTER -le 100 ]
do
    if [ $((COUNTER%15)) = 0 ]
     then
        echo "FizzBuzz"
    elif [ $((COUNTER%3)) = 0 ]
     then
        echo "Fizz"
    elif [ $((COUNTER%5)) = 0 ]
     then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    COUNTER+=1
    # $(( COUNTER++ ))
done
