#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER -ne 9 ] 
     then
        echo "Best School"
    else
        echo "Hi"
    fi
    let COUNTER+=1
done