#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=1
while [ $COUNTER -le 10 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
